baseurl = "http://docs.fluidplayer.com/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Fluid Player Documentation"
theme = "hugo-material-docs-custom"

disqusShortname = ""
googleAnalytics = ""

[menu]
    [[menu.main]]
    identifier = "overview"
    name       = "Overview"
    url        = ""
    weight     = 1

    [[menu.main]]
    identifier = "integration"
    name       = "Integration"
    url        = "integration/"
    weight     = 2

    [[menu.main]]
    identifier = "configuration"
    name       = "Configuration"
    url        = "configuration/"
    weight     = 3

    [[menu.main]]
    identifier = "wordpress"
    name       = "Wordpress"
    url        = "wordpress/"
    weight     = 3

    [[menu.main]]
    identifier = "examples"
    name       = "Demo"
    url        = "examples/"
    weight     = 4

    [[menu.main]]
    identifier = "changelog"
    name       = "Changelog"
    url        = "changelog/"
    weight     = 5

    [[menu.main]]
    identifier = "help"
    name       = "Help"
    url        = "help/"
    weight     = 6

[params]
	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

    logo = "fluid_logo.png"
    version = "2.0"

[params.palette]
    primary = "light-blue"
    accent  = "light-blue"
